# github action that checks code with Rector
name: Rector

on:
  pull_request: null

jobs:
  rector:
    runs-on: ubuntu-latest

    if: github.event.pull_request.head.repo.full_name == 'simonschaufi/php-libkml'

    steps:
      - name: "Checkout code"
        if: github.event.pull_request.head.repo.full_name == github.repository
        uses: actions/checkout@v4
        with:
          # Must be used to trigger workflow after push
          token: ${{ secrets.ACCESS_TOKEN }}

      - name: "Setup PHP"
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.1
          coverage: none

      - uses: ramsey/composer-install@v3

      - name: "Run Rector"
        run: vendor/bin/rector --ansi

      - name: "Run PHP CS Fixer"
        run: vendor/bin/php-cs-fixer fix --ansi

      - # commit only to core contributors who have repository access
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: '[TASK] Rector fixes'
